{{- if .Values.networkPolicy.enabled -}}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "deployment-platform.fullname" . }}
  labels:
    {{- include "deployment-platform.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      {{- include "deployment-platform.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: application
  policyTypes:
    - Ingress
    - Egress
  ingress:
    - from:
        {{- with .Values.networkPolicy.ingressNamespaceSelector }}
        - namespaceSelector:
            {{- toYaml . | nindent 12 }}
        {{- end }}
        - podSelector: {}
      ports:
        - protocol: TCP
          port: {{ .Values.app.port }}
  egress:
    - to:
        - namespaceSelector: {}
      ports:
        - protocol: UDP
          port: 53
        - protocol: TCP
          port: 53
    - to:
        - podSelector:
            matchLabels:
              app.kubernetes.io/component: database
      ports:
        - protocol: TCP
          port: {{ .Values.config.postgres.port }}
    - to:
        - podSelector:
            matchLabels:
              app.kubernetes.io/component: cache
      ports:
        - protocol: TCP
          port: {{ .Values.config.redis.port }}
    - to:
        - namespaceSelector: {}
      ports:
        - protocol: TCP
          port: 443
{{- end }}
