{{- if and .Values.postgresql.enabled (not .Values.postgresql.existingSecret) -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "deployment-platform.fullname" . }}-postgresql
  labels:
    {{- include "deployment-platform.labels" . | nindent 4 }}
    app.kubernetes.io/component: database
type: Opaque
stringData:
  {{- if .Values.postgresql.password }}
  password: {{ .Values.postgresql.password | quote }}
  {{- else }}
  password: "changeme"
  {{- end }}
{{- end }}
