{{- if not .Values.postgresql.enabled -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "deployment-platform.fullname" . }}
  labels:
    {{- include "deployment-platform.labels" . | nindent 4 }}
type: Opaque
stringData:
  POSTGRES_PASSWORD: {{ .Values.secrets.postgresPassword | quote }}
  {{- if .Values.secrets.redisPassword }}
  REDIS_PASSWORD: {{ .Values.secrets.redisPassword | quote }}
  {{- end }}
{{- end }}
