apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

# Prod: 3 replicas, HPA 3-20, warn logs, prod host, PDB minAvailable=2
patches:
  - target:
      kind: Deployment
      name: app
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 3
  - target:
      kind: ConfigMap
      name: deployment-platform-app
    patch: |-
      - op: replace
        path: /data/LOG_LEVEL
        value: warn
      - op: replace
        path: /data/POSTGRES_POOL_MAX
        value: "20"
  - target:
      kind: HorizontalPodAutoscaler
      name: app
    patch: |-
      - op: replace
        path: /spec/minReplicas
        value: 3
      - op: replace
        path: /spec/maxReplicas
        value: 20
  - target:
      kind: PodDisruptionBudget
      name: app
    patch: |-
      - op: replace
        path: /spec/minAvailable
        value: 2
  - target:
      kind: Ingress
      name: app
    patch: |-
      - op: replace
        path: /spec/rules/0/host
        value: app.example.com
