apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: deployment-platform-staging

resources:
  - ../../base/core
  - ../../base/optional

components:
  - ../components/staging

namePrefix: stg-
